title: Honey Momism of the Day (MOD)
email: d@summerhays.net
description: >- # this means to ignore newlines until "baseurl:"
        All {{ site.data.honey-mom-csv.size }} momisms, all in one place
keywords: momisms, mom, expressions
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://honeymom.summerhays.net" # the base hostname & protocol for your site, e.g. http://example.com
# For testing
# url: localhost:4000
icon: /assets/images/confused-smiley.png

# Build settings
markdown: kramdown
plugins:
  - jemoji
#  - jekyll-datapage-generator
#  - jekyll-coffeescript
#  - jekyll-feed

tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]

include: ['_pages',".htaccess"]

defaults:
  -
    scope:
      path: "_pages" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      permalink: ":basename"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


        # page_gen-dirs: true # uncomment, if you prefer to generate named folders
        # 
page_gen:
  - data: 'honey-mom-csv'
    template: 'dictionary'
    dir: 'fresh-dictionary'
      #    name: 'order'
    name_expr: record['order']
    title: 'momism'
